{% set name = "pytest-pep8" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 032ef7e5fa3ac30f4458c73e05bb67b0f036a8a5cb418a534b3170f89f120318

build:
  noarch: python
  number: 3
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - pytest-cache
    - pytest >=2.4.2
    - pep8 >=1.3

test:
  requires:
    - python {{ python_min }}
  imports:
    - pytest_pep8

about:
  home: https://bitbucket.org/pytest-dev/pytest-pep8
  license: MIT
  license_file: LICENSE
  summary: 'py.test plugin for efficiently checking PEP8 compliance'

extra:
  recipe-maintainers:
    - bjodah
    - nicoddemus
